Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Controllers/ClubesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data;
using Servicios;


namespace Relacion1aN_Entity_Framwork.Controllers
{
    public class ClubesController : Controller
    {
        JugadorServicio Jugadores = new JugadorServicio();
        ClubesServicios Clubes = new ClubesServicios();

        [HttpGet]
        public ActionResult Agregar()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Agregar(Club C)
        {
            Clubes.Agregar(C);
            return Redirect("/Clubes/Lista");
        }


        public ActionResult Lista()
        {
            return View(Clubes.ObtenerTodos());
        }

        [HttpGet]
        public ActionResult Modificar(int id)
        {
            Club c = Clubes.ObtenerPorId(id);
            return View(c);
        }

        [HttpPost]
        public ActionResult Modificar(Club c)
        {
            Clubes.Modificar(c);
            return Redirect("/Clubes/Lista");
        }

        public ActionResult EliminarPorId(int id)
        {

            Clubes.EliminarPorId(id);
            return RedirectToAction("Lista");
        }
    }
}

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Controllers/JugadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data;
using Servicios;
using System.ComponentModel.DataAnnotations;

namespace Relacion1aN_Entity_Framwork.Controllers
{
    public class JugadoresController : Controller
    {
        JugadorServicio Jugadores = new JugadorServicio();
        ClubesServicios Clubes = new ClubesServicios();


        [HttpGet]
        public ActionResult Agregar()
        {
            ViewBag.ListaClubes = Clubes.ObtenerTodos();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Agregar([Bind(Include = "idJugador,Apellido,Edad,idClub")] Jugador j)
        {
            ViewBag.ListaClubes = Clubes.ObtenerTodos();
            if (ModelState.IsValid)
            {

                Jugadores.Agregar(j);
                return Redirect("/Jugadores/Lista");
            }
            return View(j);
        }

        [HttpGet]
        public ActionResult Modificar(int id)
        {
            ViewBag.ListaClubes = Clubes.ObtenerTodos();
            Jugador j = Jugadores.ObtenerPorId(id);
            return View(j);
        }

        [HttpPost]
        public ActionResult Modificar(Jugador j)
        {
            Jugadores.Modificar(j);
            return RedirectToAction("Lista");
        }

        public ActionResult Lista()
        {
            return View(Jugadores.ObtenerTodos());
        }
        public ActionResult Eliminar(int id)
        {
            Jugadores.Eliminar(id);
            return Redirect("/Jugadores/Lista");
        }
    }
}

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Views/Clubes/Agregar.cshtml
@model Data.Club

@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Club</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Lista","Clubes")
</div>

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Views/Clubes/Lista.cshtml
@model List<Data.Club>

@{
    ViewBag.Title = "Clubes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Clubes</h2>

<p>
    @Html.ActionLink("Agregar Club", "Agregar")
</p>
<table class="table">
    <tr>
        <th>
            ID Club
        </th>
        <th>
            Nombre
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idClub)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.ActionLink("Modificar", "Modificar", new { id = item.idClub }) |
                @Html.ActionLink("Eliminar", "EliminarPorId", new { id = item.idClub })
            </td>
        </tr>
    }

</table>

<button class="btn btn-default">@Html.ActionLink("Volver", "Lista", "Jugadores")</button>

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Views/Clubes/Modificar.cshtml
@model Data.Club

@{
    ViewBag.Title = "Modificar";
}

<h2>Modificar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Club</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.idClub)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Lista","Clubes")
</div>

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Views/Jugadores/Agregar.cshtml
@model Data.Jugador

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Jugador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="IdClub" class="form-control">
                    @foreach (var c in ViewBag.ListaClubes)
                    {
                        <option value="@c.idClub">@c.Nombre</option>
                    }
                </select>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a Lista", "Lista")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Views/Jugadores/Lista.cshtml
@model List<Data.Jugador>
@{
    ViewBag.Title = "Lista";
}

<h2>Lista Jugadores</h2>

<table class="table">
    <tr>
        <td><strong>Id Jugador</strong></td>
        <td><strong>Apellido</strong></td>
        <td><strong>Edad</strong></td>
        <td><strong>Club</strong></td>
        <td></td>
        <td></td>
    </tr>

    @foreach (var j in Model)
    {
        <tr>
            <td>@j.idJugador</td>
            <td>@j.Apellido</td>
            <td>@j.Edad</td>
            <td>@j.Club.Nombre</td>
            <td>@Html.ActionLink("Modificar", "Modificar", new { id = j.idJugador })</td>
            <td>@Html.ActionLink("Eliminar", "Eliminar", new { id = j.idJugador })</td>
        </tr>
    }


</table>
<div class="form-group">
   
        <button class="pull-left btn btn-default">@Html.ActionLink("Ver Lista Clubes", "Lista", "Clubes")</button>
   
        <button class="pull-right btn btn-Defa">@Html.ActionLink("Agregar Jugador", "Agregar")</button>
   
</div>

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Views/Jugadores/Modificar.cshtml
@model Data.Jugador

@{
    ViewBag.Title = "Modificar2";
}

<h2>Modificar2</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Jugador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idJugador)

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="IdClub" class="form-control">
                    @foreach (var c in ViewBag.ListaClubes)
                    {
                        if (c.idClub == Model.Club.idClub)
                        {
                            <option value="@c.idClub" selected>@c.Nombre</option>
                        }
                        else
                        {
                            <option value="@c.idClub">@c.Nombre</option>
                        }

                    }
                </select>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("Volver a la lista", "Lista")
        </div>
    </div>

Relacion1aN_Entity Framwork/Relacion1aN_Entity Framwork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>